---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: semi-db
spec:
  clusterIP: None
  ports:
  - name: "mysql"
    protocol: "TCP"
    port: 3306
    targetPort: 3306
  selector:
    app: mysql
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: semi-db
spec:
  clusterIP: None
  ports:
  - name: "mongodb"
    protocol: "TCP"
    port: 27017
    targetPort: 27017
  selector:
    app: mongodb
