---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-auth
  namespace: semi-db
type: Opaque
stringData:
  root-password: rootPassword
  database: sampledb
  username: sampleuser
  password: samplePassword
---
apiVersion: v1
kind: Secret
metadata:
  name: mongo-auth
  namespace: semi-db
type: Opaque
stringData:
  root-username: rootusername
  root-password: rootPassword
  database: samplemongo